<?php
/*
Plugin Name: WordPress Plugin ReactJS
Plugin URI: http://www.
Description:
Version:
Author: Younes DRO
Author URI: http://www.
License: GPL2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain:
Domain Path: /languages
*/

/*  Copyright 2019 Younes DRO (email : younesdro at gmail.com)
    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program; if not, write to the Free Software
    Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
*/

// Make sure we don't expose any info if called directly
if ( ! function_exists( 'add_action' ) ){
  exit;
}

/*
* Adds a submenu to the Settings menu.
* the page will contain the ID of html element that hosts our JSX components.
*/
add_action( 'admin_menu', 'dro_create_menu' );
function dro_create_menu(){
  add_options_page( 'WP Plugin Using ReactJS', 'WP Plugin React', 'manage_options', __FILE__,'dro_display_menu' );
}
function dro_display_menu(){
  echo '<div id="main"></div>';
}

/**
* we enqueue the Js script generated by WebPack.
*/
add_action( 'admin_enqueue_scripts', 'dro_enqueue_script' );
function dro_enqueue_script(){
  wp_enqueue_script(
    'dro-plugin-reactjs',
    plugins_url('/dist/public/bundle.js', __FILE__) ,
    ['wp-element', 'wp-components'],
    time(), // You can add the current datetime in production env.
    true );
}
